def on_forever():
    pins.digital_write_pin(DigitalPin.P1, 1)
    led.plot(0, 4)
    led.plot(1, 3)
    led.plot(2, 2)
    led.plot(1, 1)
    led.plot(2, 1)
    led.plot(3, 1)
    led.plot(3, 2)
    led.plot(3, 3)
    basic.pause(300)
    pins.digital_write_pin(DigitalPin.P1, 0)
    led.unplot(0, 4)
    led.unplot(1, 3)
    led.unplot(2, 2)
    led.unplot(1, 1)
    led.unplot(2, 1)
    led.unplot(3, 1)
    led.unplot(3, 2)
    led.unplot(3, 3)
    basic.pause(700)
basic.forever(on_forever)
